In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/home/ashutosh/Downloads/Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [3]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [4]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [5]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [6]:
x = df.iloc[:,1:-1]
x

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [7]:
y = df.iloc[:,-1]
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [8]:
from sklearn.preprocessing import LabelEncoder
x = x.apply(LabelEncoder().fit_transform)
x

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0                8            14              4             1
1                6             9              4             1
2                4            11              3             1
3                3            10              5             1
4                7            15              4             1
..             ...           ...            ...           ...
145             24             9             28            19
146             20             4             26            15
147             22             9             28            16
148             19            13             30            19
149             16             9             27            14

[150 rows x 4 columns]

In [9]:
x.dtypes

SepalLengthCm    int64
SepalWidthCm     int64
PetalLengthCm    int64
PetalWidthCm     int64
dtype: object

In [17]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x, y, test_size=0.20,random_state=0)
xtrain

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
137             21            10             31            14
84              11             9             21            11
27               9            14              5             1
127             18             9             25            14
132             21             7             32            18
..             ...           ...            ...           ...
9                6            10              5             0
103             20             8             32            14
67              15             6             17             6
117             33            17             41            18
47               3            11              4             1

[120 rows x 4 columns]

In [18]:
xtest


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
114             15             7             27            20
62              17             1             16             6
33              12            21              4             1
107             30             8             38            14
7                7            13              5             1
100             20            12             36            21
40               7            14              3             2
86              24            10             23            11
76              25             7             24            10
71              18             7             16             9
134             18             5             32            10
51              21            11             21            11
73              18             7             23             8
54              22             7             22            11
63              18             8             23            10
37               6            10              5             0
78              17             8             21            11
90              12             5             20             8
45               5             9              4             2
16              11            18              3             3
121             13             7             25            16
66              13             9             21            11
24               5            13              8             1
8                1             8              4             1
126             19             7             24            14
22               3            15              0             1
44               8            17              8             3
97              19             8             19             9
93               7             2             10             6
26               7            13              6             3

In [19]:
ytrain

137     Iris-virginica
84     Iris-versicolor
27         Iris-setosa
127     Iris-virginica
132     Iris-virginica
            ...       
9          Iris-setosa
103     Iris-virginica
67     Iris-versicolor
117     Iris-virginica
47         Iris-setosa
Name: Species, Length: 120, dtype: object

In [20]:
ytest

114     Iris-virginica
62     Iris-versicolor
33         Iris-setosa
107     Iris-virginica
7          Iris-setosa
100     Iris-virginica
40         Iris-setosa
86     Iris-versicolor
76     Iris-versicolor
71     Iris-versicolor
134     Iris-virginica
51     Iris-versicolor
73     Iris-versicolor
54     Iris-versicolor
63     Iris-versicolor
37         Iris-setosa
78     Iris-versicolor
90     Iris-versicolor
45         Iris-setosa
16         Iris-setosa
121     Iris-virginica
66     Iris-versicolor
24         Iris-setosa
8          Iris-setosa
126     Iris-virginica
22         Iris-setosa
44         Iris-setosa
97     Iris-versicolor
93     Iris-versicolor
26         Iris-setosa
Name: Species, dtype: object

In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtrain = sc.fit_transform(xtrain)
xtest = sc.transform(xtest)
xtrain

array([[ 0.62920142,  0.10964301,  1.04272016,  0.72418792],
       [-0.56927748, -0.1253063 ,  0.19784224,  0.26357369],
       [-0.80897326,  1.04944025, -1.15396242, -1.27180705],
       [ 0.26965775, -0.1253063 ,  0.53579341,  0.72418792],
       [ 0.62920142, -0.59520492,  1.12720795,  1.33834022],
       [-0.80897326, -0.83015422, -0.3090845 ,  0.11003562],
       [-0.20973381,  1.75428817, -0.98498683, -1.11826898],
       [ 0.14980986, -0.83015422,  0.70476899,  0.41711177],
       [ 0.02996197, -0.1253063 , -0.05562113,  0.26357369],
       [-0.08988592, -1.06510353, -0.22459671, -0.19704053],
       [ 1.10859298, -0.1253063 ,  1.04272016,  1.18480214],
       [-1.4082127 ,  0.34459232, -1.322938  , -1.27180705],
       [ 1.22844087,  0.10964301,  0.70476899,  1.49187829],
       [-1.04866903,  1.04944025, -1.06947462, -0.65765475],
       [-0.56927748,  1.51933886, -1.15396242, -1.27180705],
       [-1.04866903, -2.23985008, -0.64703567, -0.50411668],
       [ 0.74904931, -0.

In [22]:
xtest

array([[-0.08988592, -0.59520492,  0.70476899,  1.64541636],
       [ 0.14980986, -2.00490077, -0.22459671, -0.50411668],
       [-0.44942959,  2.69408541, -1.23845021, -1.27180705],
       [ 1.70783243, -0.36025561,  1.6341347 ,  0.72418792],
       [-1.04866903,  0.81449094, -1.15396242, -1.27180705],
       [ 0.50935353,  0.57954163,  1.46515911,  1.79895444],
       [-1.04866903,  1.04944025, -1.322938  , -1.11826898],
       [ 0.98874509,  0.10964301,  0.36681783,  0.26357369],
       [ 1.10859298, -0.59520492,  0.45130562,  0.11003562],
       [ 0.26965775, -0.59520492, -0.22459671, -0.04350245],
       [ 0.26965775, -1.06510353,  1.12720795,  0.11003562],
       [ 0.62920142,  0.34459232,  0.19784224,  0.26357369],
       [ 0.26965775, -0.59520492,  0.36681783, -0.19704053],
       [ 0.74904931, -0.59520492,  0.28233004,  0.26357369],
       [ 0.26965775, -0.36025561,  0.36681783,  0.11003562],
       [-1.16851692,  0.10964301, -1.15396242, -1.42534512],
       [ 0.14980986, -0.

In [23]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(xtrain,ytrain)
ypred = classifier.predict(xtest)
ypred

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa'], dtype='<U15')

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
cm = confusion_matrix(ytest,ypred)
cm

array([[11,  0,  0],
       [ 0, 13,  0],
       [ 0,  0,  6]])

In [25]:
acc = accuracy_score(ytest,ypred)
acc

1.0

In [31]:
pr = precision_score(ytest,ypred,  average='macro')
pr

1.0

In [30]:
recall = recall_score(ytest, ypred, average='macro')
recall

1.0